# Dockerfile
FROM php:8.3-apache

# Apache + PHP extensions fréquentes Symfony
RUN a2enmod rewrite headers \
    && apt-get update && apt-get install -y \
        git unzip libzip-dev libicu-dev libpq-dev \
    && docker-php-ext-install intl opcache pdo pdo_mysql zip \
    && rm -rf /var/lib/apt/lists/*

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Docroot Symfony
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf \
    && sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

WORKDIR /var/www/html

# Copie du projet
COPY . .

# Dépendances prod + cache
RUN composer install --no-dev --optimize-autoloader --no-interaction \
    && php bin/console cache:clear --env=prod \
    && php bin/console cache:warmup --env=prod

# Render expose un port dynamique via $PORT.
# Apache écoute 80 dans le conteneur, Render fait le mapping.
EXPOSE 80
