<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZhsAhfW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZhsAhfW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZhsAhfW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZhsAhfW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZhsAhfW\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZhsAhfW',
    'container.build_id' => 'b20a201c',
    'container.build_time' => 1737420444,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZhsAhfW');
