<?php

namespace ContainerZhsAhfW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_XYscAu9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.XYscAu9' shared service.
     *
     * @return \Symfony\Component\PasswordHasher\UserPasswordHasherInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\RegistrationController::register()": the $passwordHasher argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\PasswordHasher\\UserPasswordHasherInterface".');
    }
}
