<?php

namespace ContainerZhsAhfW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerregisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R4z0gxb.App\Controller\RegistrationController::register()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R4z0gxb.App\\Controller\\RegistrationController::register()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'passwordHasher' => ['privates', '.errored.XYscAu9', NULL, 'Cannot determine controller argument for "App\\Controller\\RegistrationController::register()": the $passwordHasher argument is type-hinted with the non-existent class or interface: "Symfony\\Component\\PasswordHasher\\UserPasswordHasherInterface".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'passwordHasher' => '?',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\RegistrationController::register()', $container);
    }
}
